-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url VARCHAR(60)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url)
values
  ('Nordstrom', 'https://www.nordstrom.com/?origin=tab-logo'),
  ('Forever 21', 'https://www.forever21.com/us/shop'),
  ('Sephora', 'https://www.sephora.com/')
  ('Free People, 'https://www.freepeople.com/),
  ('H&M', 'https://www2.hm.com/en_us/women.html'),
  ('J Crew', 'https://www.jcrew.com/')
  ('Ralph Lauren, 'http://www.ralphlauren.com/home/index.jsp?ab=global_logo'),
  ('ASOS', 'https://www.asos.com/us/women/'),
  ('Tobi', 'https://www.tobi.com/'),
  ('Express', 'https://www.express.com/home.jsp');
